blank_issues_enabled: false
contact_links:
  - name: ğŸ§ man
    url: https://github.com/liebespaar93/
    about: man is here!
  - name: ğŸ’¡ test
    url: https://github.com/liebespaar93/goingfree_004/
    about: test
 
 
